// frontend-web/webclient/app/SiteComponents/Applications/Applications.jsx
import React from 'react';
import LoadingIcon from '../LoadingIcon';
import {Link} from 'react-router';
import "../../components/Tables/Datatable.scss";

import {Table} from 'react-bootstrap';
import {Card, CardHeading} from "../Cards";
import pubsub from "pubsub-js";
import {Cloud} from "../../../authentication/SDUCloudObject";

class Applications extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            loading: false,
            applications: [],
        }
    }

    componentDidMount() {
        pubsub.publish('setPageTitle', this.constructor.name);
        this.getApplications();
    }

    getApplications() {
        this.setState({loading: true});
        Cloud.get("/hpc/apps").then(apps => {
            this.setState({
                applications: apps,
                loading: false
            });
        });
    }

    render() {
        return (
            <section>
                <div className="container-fluid">
                    <div className="col-lg-10">
                        <LoadingIcon loading={!this.state.applications.length}/>
                        <Card xs={6} sm={12}>
                            <div className="card-body">
                                <Table className="table table-hover mv-lg">
                                    <thead>
                                    <tr>
                                        <th>Visibility</th>
                                        <th>Application Name</th>
                                        <th>Version</th>
                                        <th/>
                                    </tr>
                                    </thead>
                                    <ApplicationsList applications={this.state.applications}/>
                                </Table>
                            </div>
                        </Card>
                    </div>
                    <div className="col-lg-2 visible-lg">
                        <div>
                            <button className="btn btn-primary ripple btn-block"><span className="ion-android-upload pull-left"/> Upload Application
                            </button>
                            <br/>
                            <hr/>
                        </div>
                    </div>
                </div>
            </section>)
    }
}

function ApplicationsList(props) {
    let applications = props.applications.slice();
    let i = 0;
    let applicationsList = applications.map(app =>
        <SingleApplication key={i++} app={app}/>
    );
    return (
        <tbody>
        {applicationsList}
        </tbody>)
}

function SingleApplication(props) {
    return (
        <tr className="gradeA row-settings">
            <PrivateIcon isPrivate={props.app.info.isPrivate}/>
            <td title={props.app.info.description}>{props.app.info.name}</td>
            <td title={props.app.info.description}>{props.app.info.version}</td>
            <th>
                <Link to={'/applications/' + props.app.info.name + '/' + props.app.info.version}>
                    <button className="btn btn-info">Run</button>
                </Link>
            </th>
        </tr>
    )
}

function PrivateIcon(props) {
    if (props.isPrivate) {
        return (
            <td title="The app is private and can only be seen by the creator and people it was shared with">
                <em className="ion-locked"/></td>
        )
    } else {
        return (<td title="The application is openly available for everyone"><em className="ion-unlocked"/></td>)
    }
}

export default Applications

// web/app/src/components/Applications.vue
<template>
  <!-- Page content-->
  <section xmlns:v-on="http://www.w3.org/1999/xhtml">
    <div class="container-fluid">
      <!-- DATATABLE DEMO 1-->
      <div class="col-lg-10">
        <loading-icon v-if="!applications.length"></loading-icon>
        <div v-cloak class="card" v-if="applications.length">
          <div class="card-body">
            <table id="table-options" class="table-datatable table table-striped table-hover mv-lg">
              <thead>
              <tr>
                <th></th>
                <th>Application Name</th>
                <th>Author</th>
                <th>Rating</th>
                <th class="sort-numeric">Version</th>
                <th></th>
              </tr>
              </thead>
              <tbody v-cloak>
              <tr class="gradeA row-settings" v-for="app in applications">
                <td v-if="app.info.private"
                    title="The app is private and can only be seen by the creator and people it was shared with">
                  <em class="ion-locked"></em></td>
                <td v-else title='The application is openly available for everyone'><em
                  class="ion-unlocked"></em></td>
                <td v-bind:title="app.info.description">{{ app.info.name }}</td>
                <td v-bind:title="app.info.description">{{ app.info.author }}</td>
                <td title="Rating for the application">{{ app.info.rating }} / 5</td>
                <td v-bind:title="app.info.description">{{ app.info.version }}</td>
                <th>
                  <a v-bind:href="'/runApp/' + app.info.name + '/' + app.info.version "><button class="btn btn-info">Run</button></a>
                </th>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-2 visible-lg">
        <div>
          <button class="btn btn-primary ripple btn-block ion-android-upload"> Upload Application</button>
          <br>
          <hr>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
  import $ from 'jquery'
  import LoadingIcon from "./LoadingIcon";

  export default {
    components: {LoadingIcon},
    name: 'applications',
    data() {
      return {
        applications: [],
      }
    },
    mounted() {
      this.getApplications();
    },
    methods: {
      getApplications: function () {
        $.getJSON("/api/getApplications").then((data) => {
          this.applications = data;
        });
      },
      newApplication: function () {
        console.log("Empty");
      }
    }
  }

</script>
