// webclient/app/SiteComponents/Applications/RunApp.jsx
import React from 'react';
import {getMockApp} from '../../MockObjects'
import FileSelector from '../FileSelector'

class RunApp extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            loading: false,
            appName: props.params.appName,
            appVersion: props.params.appVersion,
            app: null,
        };
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    componentDidMount() {
        this.getApplication();
    }

    handleSubmit(event) {
        console.log("Submitted");
        event.preventDefault();
    }

    handleInputChange(parameterName, event) {
        let app = this.state.app;
        app.parameters[parameterName].value = event.target.value;
        this.setState(() => {
            app: app
        });
        event.preventDefault();
    }

    handleFileSelectorChange() {
        console.log("Oy");
    }

    getApplication() {
        this.setState({
            loading: true
        });
        // FIXME ACTUAL APPLICATION
        {
            let app = getMockApp(this.state.appName, this.state.appVersion);
            this.setState({app: app});
            this.setState({loading: false});
        }
        // FIXME END
    }


    render() {
        return (
            <section>
                <div className="container-fluid">
                    <div className="card">
                        <div className="card-body">
                            <ApplicationHeader app={this.state.app}/>
                            <hr/>
                            <Parameters app={this.state.app} handleSubmit={this.handleSubmit}
                                        onChange={this.handleInputChange}
                                        onFileSelectionChange={this.handleFileSelectorChange}/>
                        </div>
                    </div>
                </div>
            </section>)
    }
}

function ApplicationHeader(props) {
    if (!props.app) {
        return null
    }
    return (
        <div>
            <h1>{props.app.info.name}</h1>
            <h3>{props.app.info.description}</h3>
            <h4>Author: {props.app.info.author}</h4>
        </div>)
}


function Parameters(props) {
    if (!props.app) {
        return null
    }
    let parameters = props.app.parameters.slice();
    let i = 0;
    let parametersList = parameters.map(parameter =>
        <Parameter key={i++} parameter={parameter} onChange={props.onChange} onFileSelectionChange={props.onFileSelectionChange}/>
    );
    return (
        <form onSubmit={props.handleSubmit} className="form-horizontal">
            {parametersList}
            <input value="Submit" className="btn btn-info" type="submit"/>
        </form>
    )

}

// Types: input, output, int, float, string
function Parameter(props) {
    let parameter;
    if (props.parameter.type === "input_file") {
        parameter = (<InputFileParameter onFileSelectionChange={props.onFileSelectionChange} parameter={props.parameter}/>);
    } else if (props.parameter.type === "output_file") {
        parameter = (<OutputFileParameter parameter={props.parameter}/>);
    } else if (props.parameter.type === "integer") {
        parameter = (<IntegerParameter parameter={props.parameter}/>);
    } else if (props.parameter.type === "float") {
        parameter = (<FloatParameter parameter={props.parameter}/>);
    } else if (props.parameter.type === "text") {
        parameter = (<TextParameter parameter={props.parameter}/>);
    }

    return (
        <fieldset>
            {parameter}
        </fieldset>)
}

function InputFileParameter(props) {
    return (
        <div className="form-group">
            <label className="col-sm-2 control-label">{props.parameter.prettyName}</label>
            <div className="col-md-4">
                <FileSelector onFileSelectionChange={props.onFileSelectionChange}/>
                <span><em/></span>
                <span className="help-block">Source of the file</span>
                <input
                    placeholder={props.parameter.defaultValue ? 'Default value: ' + props.parameter.defaultValue : ''}
                    required={!props.parameter.isOptional}
                    className="form-control"
                    type="text"/>
                <div>Destination of the file</div>
            </div>
        </div>)
}

function OutputFileParameter(props) {
    return (
        <div className="form-group">
            <label className="col-sm-2 control-label">{props.parameter.prettyName}</label>
            <div className="col-md-4">
                <input required={!props.parameter.isOptional}
                       className="form-control" type="text"/>
                <span className="help-block">Source of the file</span>
                <file-selector select="updateParam(index, 'destination', $event)"/>
                <span className="help-block">Destination of the file.</span>
            </div>
        </div>
    )
}

function TextParameter(props) {
    return (
        <div className="form-group">
            <label className="col-sm-2 control-label">{props.parameter.prettyName}</label>
            <div className="col-md-4">
                <input id="parameter.name"
                       placeholder={props.parameter.defaultValue ? "Default value: " + props.parameter.defaultValue : ""}
                       required={!props.parameter.isOptional}
                       name="parameter.name"
                       className="form-control"
                       type="text"/>
                <span className="help-block">{props.parameter.description}</span>
            </div>
        </div>
    )
}

function IntegerParameter(props) {
    return (
        <div className="form-group">
            <label
                className="col-sm-2 control-label">{props.parameter.prettyName}</label>
            <div className="col-md-4">
                <input id="parameter.name"
                       placeholder={props.parameter.defaultValue ? "Default value: " + props.parameter.defaultValue : ""}
                       required={!props.parameter.isOptional} name={props.parameter.name}
                       className="form-control"
                       type="number"
                       step="1"/>
                <span className="help-block">{props.parameter.description}</span>
            </div>
        </div>);
}

function FloatParameter(props) {
    return (
        <div className="form-group">
            <label
                className="col-sm-2 control-label">{props.parameter.prettyName}</label>
            <div className="col-md-4">
                <input id="parameter.name"
                       placeholder={props.parameter.defaultValue ? "Default value: " + props.parameter.defaultValue : ""}
                       required={!props.parameter.isOptional} name={props.parameter.name}
                       className="form-control"
                       type="number"
                       step="any"/>
                <span className="help-block">{props.parameter.description}</span>
            </div>
        </div>
    )
}

export default RunApp

// web/app/src/components/RunAppComponent.vue
<template>
  <section xmlns:v-on="http://www.w3.org/1999/xhtml">
    <div class="container-fluid">
      <div class="card">
        <div class="card-body">
          <div v-cloak v-if="application.info">
            <h1>{{ application.info.name }}</h1>
            <h3>{{ application.info.description }}</h3>
            <h4>Author: {{ application.info.author }}</h4>
          </div>
          <hr>
          <form id="run-app" v-on:submit.prevent="submit" class="form-horizontal">
            <fieldset v-for="parameter, index in application.parameters">
              <div class="form-group" v-if="parameter.type === 'input_file'">
                <label class="col-sm-2 control-label">{{parameter.prettyName}}</label>
                <div class="col-md-4">
                  <file-selector @select="updateParam(index, 'source', $event)" :id="parameter.name + '-src'"></file-selector>
                  <span><em :id="parameter.name + '-src-error'"></em></span>
                  <span class="help-block">Source of the file</span>
                  <input v-bind:id="parameter.name + '-dst'"
                         :placeholder="parameter.defaultValue ? 'Default value: ' + parameter.defaultValue : ''"
                         :required="!parameter.optional" v-model="parameter.destination" class="form-control"
                         type="text">
                  <div>Destination of the file</div>
                </div>
              </div>
              <!--<div v-else-if="parameter.type === 'output_file'" class="form-group">
                <label v-bind:for="parameter.name" class="col-sm-2 control-label">{{parameter.prettyName}}</label>
                <div class="col-md-4">
                  <input v-bind:id="parameter.name" :required="!parameter.optional" v-model="parameter.source" class="form-control" type="text">
                  <span class="help-block">Source of the file</span>
                  <file-selector @select="updateParam(index, 'destination', $event)"></file-selector>
                  <span class="help-block">Destination of the file.</span>
                  </div>
              </div>-->
              <div class="form-group" v-else-if="parameter.type === 'float'">
                <label v-bind:for="parameter.name" class="col-sm-2 control-label">{{parameter.prettyName}}</label>
                <div class="col-md-4">
                  <input v-bind:id="parameter.name"
                         :placeholder="parameter.defaultValue ? 'Default value: ' + parameter.defaultValue : ''"
                         :required="!parameter.optional" :name="parameter.name" class="form-control"
                         type="number"
                         step="any" v-model="parameter.content">
                  <span class="help-block">{{ parameter.description }}</span>
                </div>
              </div>
              <div class="form-group" v-else-if="parameter.type === 'integer'">
                <label v-bind:for="parameter.name" class="col-sm-2 control-label">{{parameter.prettyName}}</label>
                <div class="col-md-4">
                  <input v-bind:id="parameter.name"
                         :placeholder="parameter.defaultValue ? 'Default value: ' + parameter.defaultValue : ''"
                         :required="!parameter.optional" :name="parameter.name" class="form-control"
                         type="number"
                         step="1" v-model="parameter.content">
                  <span class="help-block">{{ parameter.description }}</span>
                </div>
              </div>
              <div class="form-group" v-else-if="parameter.type === 'text'">
                <label v-bind:for="parameter.name" class="col-sm-2 control-label">{{parameter.prettyName}}</label>
                <div class="col-md-4">
                  <input v-bind:id="parameter.name"
                         :placeholder="parameter.defaultValue ? 'Default value: ' + parameter.defaultValue : ''"
                         :required="!parameter.optional" v-model="parameter.content" :name="parameter.name"
                         class="form-control"
                         type="text">
                  <span class="help-block">{{ parameter.description }}</span>
                </div>
              </div>
            </fieldset>
            <input value="Submit" :click="submit" class="btn btn-info" type="submit">
          </form>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
  import Vue from 'vue'
  import FileSelector from './FileSelector.vue'

  Vue.component('file-selector', FileSelector);

  export default {
    name: 'run-app-component',
    props: {application: Object},
    methods: {
      updateParam(index, type, payload) {
        this.application.parameters[index][type] = payload
      },
      validateInputFields(parameters) {
        for (let i = 0; i < parameters.length; i++) {
          let current = parameters[i];
          switch (current.type) {
            case 'input_file':
              if (!current.optional)
                if (!current.source) {
                  document.getElementById(current.name + '-src-error').innerText = "Please select a file as input.";
                  return false;
                } else if (!current.destination) {
                  document.getElementById(current.name + '-dst').focus();
                  return false;
                }
              break;
          }
        }
        return true;
      },
      submit() {
        if (!this.validateInputFields(this.application.parameters)) return;

        let parameters = Array.from(this.application.parameters);

        let app = {
          name: this.application.info.name,
          version: this.application.info.version,
          parameters: {}
        };

        parameters.forEach((it) => {
          switch (it.type) {
            case 'input_file':
              if (it.source) {
                app.parameters[it.name] = {
                  source: it.source.path.uri,
                  destination: it.destination
                };
              }
              break;
            /*case 'output_file': // FIXME find out if I am dead code, or to be used later
              if (it.destination) {
                app.parameters[it.name] = {
                  destination: it.destination.path.uri,
                  source: it.source
                };
              }
              break;*/
            case 'float':
            case 'integer':
            case 'text':
              app.parameters[it.name] = it.content;
              break;
          }
        });

        $.post("/api/startJob/", {application: JSON.stringify(app)}, () => {
          window.location.href = "/analyses/";
        })
      }
    }
  }
</script>
